version: '3.8'

services:
  # 云服务 - 简化版
  cloud-http-service:
    build:
      context: ./services/cloud-http-service
      dockerfile: Dockerfile
    container_name: cloud-http-service
    ports:
      - "9110:9110"
    environment:
      - NODE_ENV=production
    volumes:
      - ./services/cloud-http-service/logs:/app/logs
    restart: unless-stopped

  # 家用服务 - 简化版
  home-http-service:
    build:
      context: ./services/home-http-service
      dockerfile: Dockerfile
    container_name: home-http-service
    ports:
      - "9111:9111"
    environment:
      - NODE_ENV=production
    volumes:
      - ./services/home-http-service/logs:/app/logs
    restart: unless-stopped
    depends_on:
      - cloud-http-service

  # DDNS工具 - 简化版
  ddns-tool:
    build:
      context: ./tools/ddns-tool
      dockerfile: Dockerfile
    container_name: ddns-tool
    ports:
      - "9910:9910"
    environment:
      - NODE_ENV=production
    volumes:
      - ./tools/ddns-tool/logs:/app/logs
      - ./tools/ddns-tool/cache:/app/cache
    restart: unless-stopped
    depends_on:
      - cloud-http-service

networks:
  default:
    name: work-work-simple 